//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class Account
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Number
        {
            get;
            set;
        }
    
        public virtual string PIN
        {
            get;
            set;
        }
    
        public virtual string ComebackURL
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual string InsertUserName
        {
            get;
            set;
        }
    
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }
    
        public virtual string UpdateUserName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public virtual int BankId
        {
            get { return _bankId; }
            set
            {
                if (_bankId != value)
                {
                    if (BankEntity != null && BankEntity.Id != value)
                    {
                        BankEntity = null;
                    }
                    _bankId = value;
                }
            }
        }
        private int _bankId;
    
        public virtual string MerchantId
        {
            get;
            set;
        }
    
        public virtual string TerminalId
        {
            get;
            set;
        }
    
        public virtual string PaymentUrl
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Bank BankEntity
        {
            get { return _bankEntity; }
            set
            {
                if (!ReferenceEquals(_bankEntity, value))
                {
                    var previousValue = _bankEntity;
                    _bankEntity = value;
                    FixupBankEntity(previousValue);
                }
            }
        }
        private Bank _bankEntity;

        #endregion
        #region Association Fixup
    
        private void FixupBankEntity(Bank previousValue)
        {
            if (previousValue != null && previousValue.Account.Contains(this))
            {
                previousValue.Account.Remove(this);
            }
    
            if (BankEntity != null)
            {
                if (!BankEntity.Account.Contains(this))
                {
                    BankEntity.Account.Add(this);
                }
                if (BankId != BankEntity.Id)
                {
                    BankId = BankEntity.Id;
                }
            }
        }

        #endregion
    }
}
