//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class Attachment
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string RefrenceType
        {
            get;
            set;
        }
    
        public virtual int RefrenceID
        {
            get;
            set;
        }
    
        public virtual int CategoryLookupID
        {
            get { return _categoryLookupID; }
            set
            {
                if (_categoryLookupID != value)
                {
                    if (CategoryLookupEntity != null && CategoryLookupEntity.Id != value)
                    {
                        CategoryLookupEntity = null;
                    }
                    _categoryLookupID = value;
                }
            }
        }
        private int _categoryLookupID;
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual byte[] Image
        {
            get;
            set;
        }
    
        public virtual string InsertUserName
        {
            get;
            set;
        }
    
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }
    
        public virtual string UpdateUserName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public virtual string Filename
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Lookup CategoryLookupEntity
        {
            get { return _categoryLookupEntity; }
            set
            {
                if (!ReferenceEquals(_categoryLookupEntity, value))
                {
                    var previousValue = _categoryLookupEntity;
                    _categoryLookupEntity = value;
                    FixupCategoryLookupEntity(previousValue);
                }
            }
        }
        private Lookup _categoryLookupEntity;

        #endregion
        #region Association Fixup
    
        private void FixupCategoryLookupEntity(Lookup previousValue)
        {
            if (previousValue != null && previousValue.Attachments.Contains(this))
            {
                previousValue.Attachments.Remove(this);
            }
    
            if (CategoryLookupEntity != null)
            {
                if (!CategoryLookupEntity.Attachments.Contains(this))
                {
                    CategoryLookupEntity.Attachments.Add(this);
                }
                if (CategoryLookupID != CategoryLookupEntity.Id)
                {
                    CategoryLookupID = CategoryLookupEntity.Id;
                }
            }
        }

        #endregion
    }
}
