//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class CertificatRequest : Request
    {
        #region Primitive Properties
    
        public virtual byte CertificateStatus
        {
            get;
            set;
        }
    
        public virtual string ExperienceHour
        {
            get;
            set;
        }
    
        public virtual string ExperienceYear
        {
            get;
            set;
        }
    
        public virtual string MedicalClass
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> MedicalClassExpiryDate
        {
            get;
            set;
        }
    
        public virtual string PreviousLicenceType
        {
            get;
            set;
        }
    
        public virtual string PreviousLicenceIDNo
        {
            get;
            set;
        }
    
        public virtual string TrainingCourse
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> FirstTimeParticipation
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LatestParticipationDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<CertificateResult> CertificateResults
        {
            get
            {
                if (_certificateResults == null)
                {
                    var newCollection = new FixupCollection<CertificateResult>();
                    newCollection.CollectionChanged += FixupCertificateResults;
                    _certificateResults = newCollection;
                }
                return _certificateResults;
            }
            set
            {
                if (!ReferenceEquals(_certificateResults, value))
                {
                    var previousValue = _certificateResults as FixupCollection<CertificateResult>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCertificateResults;
                    }
                    _certificateResults = value;
                    var newValue = value as FixupCollection<CertificateResult>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCertificateResults;
                    }
                }
            }
        }
        private ICollection<CertificateResult> _certificateResults;

        #endregion
        #region Association Fixup
    
        private void FixupCertificateResults(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CertificateResult item in e.NewItems)
                {
                    item.CertificatRequest = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CertificateResult item in e.OldItems)
                {
                    if (ReferenceEquals(item.CertificatRequest, this))
                    {
                        item.CertificatRequest = null;
                    }
                }
            }
        }

        #endregion
    }
}
