//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class CertificateResult
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ExamDate
        {
            get;
            set;
        }
    
        public virtual int CertificatRequestId
        {
            get { return _certificatRequestId; }
            set
            {
                if (_certificatRequestId != value)
                {
                    if (CertificatRequest != null && CertificatRequest.Id != value)
                    {
                        CertificatRequest = null;
                    }
                    _certificatRequestId = value;
                }
            }
        }
        private int _certificatRequestId;
    
        public virtual string IDNo
        {
            get;
            set;
        }
    
        public virtual string WrittenExamResult
        {
            get;
            set;
        }
    
        public virtual string WrittenExamResultComment
        {
            get;
            set;
        }
    
        public virtual string OralExamResult
        {
            get;
            set;
        }
    
        public virtual string OralExamResultComment
        {
            get;
            set;
        }
    
        public virtual string Reaks
        {
            get;
            set;
        }
    
        public virtual string InsertUserName
        {
            get;
            set;
        }
    
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }
    
        public virtual string UpdateUserName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> TaskInstanceID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CertificatRequest CertificatRequest
        {
            get { return _certificatRequest; }
            set
            {
                if (!ReferenceEquals(_certificatRequest, value))
                {
                    var previousValue = _certificatRequest;
                    _certificatRequest = value;
                    FixupCertificatRequest(previousValue);
                }
            }
        }
        private CertificatRequest _certificatRequest;

        #endregion
        #region Association Fixup
    
        private void FixupCertificatRequest(CertificatRequest previousValue)
        {
            if (previousValue != null && previousValue.CertificateResults.Contains(this))
            {
                previousValue.CertificateResults.Remove(this);
            }
    
            if (CertificatRequest != null)
            {
                if (!CertificatRequest.CertificateResults.Contains(this))
                {
                    CertificatRequest.CertificateResults.Add(this);
                }
                if (CertificatRequestId != CertificatRequest.Id)
                {
                    CertificatRequestId = CertificatRequest.Id;
                }
            }
        }

        #endregion
    }
}
