//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class ContactInfoCTP
    {
        #region Primitive Properties
    
        public string Tel
        {
            get;
            set;
        }
    
        public string Mobile
        {
            get;
            set;
        }
    
        public string Fax
        {
            get;
            set;
        }
    
        public string Email1
        {
            get;
            set;
        }
    
        public string Email2
        {
            get;
            set;
        }
    
        public string address
        {
            get;
            set;
        }

        #endregion
    }
}
