//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class EPaymentStatus
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual short Status
        {
            get;
            set;
        }
    
        public virtual string InsertUserName
        {
            get;
            set;
        }
    
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }
    
        public virtual int EPaymentHistoryId
        {
            get { return _ePaymentHistoryId; }
            set
            {
                if (_ePaymentHistoryId != value)
                {
                    if (EPaymentHistoryEntity != null && EPaymentHistoryEntity.Id != value)
                    {
                        EPaymentHistoryEntity = null;
                    }
                    _ePaymentHistoryId = value;
                }
            }
        }
        private int _ePaymentHistoryId;
    
        public virtual string TrackCode
        {
            get;
            set;
        }
    
        public virtual string AppStatus
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual EPaymentHistory EPaymentHistoryEntity
        {
            get { return _ePaymentHistoryEntity; }
            set
            {
                if (!ReferenceEquals(_ePaymentHistoryEntity, value))
                {
                    var previousValue = _ePaymentHistoryEntity;
                    _ePaymentHistoryEntity = value;
                    FixupEPaymentHistoryEntity(previousValue);
                }
            }
        }
        private EPaymentHistory _ePaymentHistoryEntity;

        #endregion
        #region Association Fixup
    
        private void FixupEPaymentHistoryEntity(EPaymentHistory previousValue)
        {
            if (previousValue != null && previousValue.EPaymentStatus.Contains(this))
            {
                previousValue.EPaymentStatus.Remove(this);
            }
    
            if (EPaymentHistoryEntity != null)
            {
                if (!EPaymentHistoryEntity.EPaymentStatus.Contains(this))
                {
                    EPaymentHistoryEntity.EPaymentStatus.Add(this);
                }
                if (EPaymentHistoryId != EPaymentHistoryEntity.Id)
                {
                    EPaymentHistoryId = EPaymentHistoryEntity.Id;
                }
            }
        }

        #endregion
    }
}
