//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class ExamScheduleHistory
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int ExamScheduleId
        {
            get { return _examScheduleId; }
            set
            {
                if (_examScheduleId != value)
                {
                    if (ExamScheduleEntity != null && ExamScheduleEntity.Id != value)
                    {
                        ExamScheduleEntity = null;
                    }
                    _examScheduleId = value;
                }
            }
        }
        private int _examScheduleId;
    
        public virtual int ExamId
        {
            get;
            set;
        }
    
        public virtual System.DateTime ScheduleDate
        {
            get;
            set;
        }
    
        public virtual short Capacity
        {
            get;
            set;
        }
    
        public virtual string InsertUserName
        {
            get;
            set;
        }
    
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }
    
        public virtual string UpdateUserName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public virtual string HistoryInsertUserName
        {
            get;
            set;
        }
    
        public virtual System.DateTime HistoryInsertDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ExamSchedule ExamScheduleEntity
        {
            get { return _examScheduleEntity; }
            set
            {
                if (!ReferenceEquals(_examScheduleEntity, value))
                {
                    var previousValue = _examScheduleEntity;
                    _examScheduleEntity = value;
                    FixupExamScheduleEntity(previousValue);
                }
            }
        }
        private ExamSchedule _examScheduleEntity;

        #endregion
        #region Association Fixup
    
        private void FixupExamScheduleEntity(ExamSchedule previousValue)
        {
            if (previousValue != null && previousValue.ExamScheduleHistories.Contains(this))
            {
                previousValue.ExamScheduleHistories.Remove(this);
            }
    
            if (ExamScheduleEntity != null)
            {
                if (!ExamScheduleEntity.ExamScheduleHistories.Contains(this))
                {
                    ExamScheduleEntity.ExamScheduleHistories.Add(this);
                }
                if (ExamScheduleId != ExamScheduleEntity.Id)
                {
                    ExamScheduleId = ExamScheduleEntity.Id;
                }
            }
        }

        #endregion
    }
}
