//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class ExamRequest : Request
    {
        #region Primitive Properties
    
        public virtual int ExamTypeID
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> RequestedExamDate
        {
            get;
            set;
        }
    
        public virtual byte RequestExamStatus
        {
            get;
            set;
        }

        #endregion
    }
}
