//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class FlightExperts : Person
    {
        #region Navigation Properties
    
        public virtual ICollection<FlightExpert_Certificate> FlightExpert_Certificates
        {
            get
            {
                if (_flightExpert_Certificates == null)
                {
                    var newCollection = new FixupCollection<FlightExpert_Certificate>();
                    newCollection.CollectionChanged += FixupFlightExpert_Certificates;
                    _flightExpert_Certificates = newCollection;
                }
                return _flightExpert_Certificates;
            }
            set
            {
                if (!ReferenceEquals(_flightExpert_Certificates, value))
                {
                    var previousValue = _flightExpert_Certificates as FixupCollection<FlightExpert_Certificate>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFlightExpert_Certificates;
                    }
                    _flightExpert_Certificates = value;
                    var newValue = value as FixupCollection<FlightExpert_Certificate>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFlightExpert_Certificates;
                    }
                }
            }
        }
        private ICollection<FlightExpert_Certificate> _flightExpert_Certificates;

        #endregion
        #region Association Fixup
    
        private void FixupFlightExpert_Certificates(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (FlightExpert_Certificate item in e.NewItems)
                {
                    item.FlightExpertEntity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FlightExpert_Certificate item in e.OldItems)
                {
                    if (ReferenceEquals(item.FlightExpertEntity, this))
                    {
                        item.FlightExpertEntity = null;
                    }
                }
            }
        }

        #endregion
    }
}
