//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class LookupType
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int Code
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Lookup> Lookups
        {
            get
            {
                if (_lookups == null)
                {
                    var newCollection = new FixupCollection<Lookup>();
                    newCollection.CollectionChanged += FixupLookups;
                    _lookups = newCollection;
                }
                return _lookups;
            }
            set
            {
                if (!ReferenceEquals(_lookups, value))
                {
                    var previousValue = _lookups as FixupCollection<Lookup>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLookups;
                    }
                    _lookups = value;
                    var newValue = value as FixupCollection<Lookup>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLookups;
                    }
                }
            }
        }
        private ICollection<Lookup> _lookups;

        #endregion
        #region Association Fixup
    
        private void FixupLookups(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Lookup item in e.NewItems)
                {
                    item.LookupTypeEntity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Lookup item in e.OldItems)
                {
                    if (ReferenceEquals(item.LookupTypeEntity, this))
                    {
                        item.LookupTypeEntity = null;
                    }
                }
            }
        }

        #endregion
    }
}
