//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class RequestType
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual int Code
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Request> Requests
        {
            get
            {
                if (_requests == null)
                {
                    var newCollection = new FixupCollection<Request>();
                    newCollection.CollectionChanged += FixupRequests;
                    _requests = newCollection;
                }
                return _requests;
            }
            set
            {
                if (!ReferenceEquals(_requests, value))
                {
                    var previousValue = _requests as FixupCollection<Request>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRequests;
                    }
                    _requests = value;
                    var newValue = value as FixupCollection<Request>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRequests;
                    }
                }
            }
        }
        private ICollection<Request> _requests;

        #endregion
        #region Association Fixup
    
        private void FixupRequests(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Request item in e.NewItems)
                {
                    item.RequestTypeEntity = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Request item in e.OldItems)
                {
                    if (ReferenceEquals(item.RequestTypeEntity, this))
                    {
                        item.RequestTypeEntity = null;
                    }
                }
            }
        }

        #endregion
    }
}
