//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CAOCertificate.BusinessObjects
{
    public partial class Seat
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int ExamScheduleId
        {
            get { return _examScheduleId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_examScheduleId != value)
                    {
                        if (ExamScheduleEntity != null && ExamScheduleEntity.Id != value)
                        {
                            ExamScheduleEntity = null;
                        }
                        _examScheduleId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _examScheduleId;
    
        public virtual Nullable<int> RequestId
        {
            get { return _requestId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_requestId != value)
                    {
                        if (RequestEntity != null && RequestEntity.Id != value)
                        {
                            RequestEntity = null;
                        }
                        _requestId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _requestId;
    
        public virtual Nullable<System.DateTime> ReserveUntilDate
        {
            get;
            set;
        }
    
        public virtual string InsertUserName
        {
            get;
            set;
        }
    
        public virtual System.DateTime InsertDate
        {
            get;
            set;
        }
    
        public virtual string UpdateUserName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdateDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> TaskInstanceId
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Request RequestEntity
        {
            get { return _requestEntity; }
            set
            {
                if (!ReferenceEquals(_requestEntity, value))
                {
                    var previousValue = _requestEntity;
                    _requestEntity = value;
                    FixupRequestEntity(previousValue);
                }
            }
        }
        private Request _requestEntity;
    
        public virtual ExamSchedule ExamScheduleEntity
        {
            get { return _examScheduleEntity; }
            set
            {
                if (!ReferenceEquals(_examScheduleEntity, value))
                {
                    var previousValue = _examScheduleEntity;
                    _examScheduleEntity = value;
                    FixupExamScheduleEntity(previousValue);
                }
            }
        }
        private ExamSchedule _examScheduleEntity;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupRequestEntity(Request previousValue)
        {
            if (previousValue != null && previousValue.Seats.Contains(this))
            {
                previousValue.Seats.Remove(this);
            }
    
            if (RequestEntity != null)
            {
                if (!RequestEntity.Seats.Contains(this))
                {
                    RequestEntity.Seats.Add(this);
                }
                if (RequestId != RequestEntity.Id)
                {
                    RequestId = RequestEntity.Id;
                }
            }
            else if (!_settingFK)
            {
                RequestId = null;
            }
        }
    
        private void FixupExamScheduleEntity(ExamSchedule previousValue)
        {
            if (previousValue != null && previousValue.Seats.Contains(this))
            {
                previousValue.Seats.Remove(this);
            }
    
            if (ExamScheduleEntity != null)
            {
                if (!ExamScheduleEntity.Seats.Contains(this))
                {
                    ExamScheduleEntity.Seats.Add(this);
                }
                if (ExamScheduleId != ExamScheduleEntity.Id)
                {
                    ExamScheduleId = ExamScheduleEntity.Id;
                }
            }
        }

        #endregion
    }
}
